// <auto-generated />
using System;
using BlazorPeliculasSa.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorPeliculasSa.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200426034523_personasPrueba2")]
    partial class personasPrueba2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.2.20159.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlazorPeliculasSa.Shared.Entidades.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("BlazorPeliculasSa.Shared.Entidades.GeneroPelicula", b =>
                {
                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<int>("PeliculaId")
                        .HasColumnType("int");

                    b.HasKey("GeneroId", "PeliculaId");

                    b.HasIndex("PeliculaId");

                    b.ToTable("GenerosPeliculas");
                });

            modelBuilder.Entity("BlazorPeliculasSa.Shared.Entidades.Pelicula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("EnCartelera")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Lanzamiento")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Poster")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resumen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trailer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Peliculas");
                });

            modelBuilder.Entity("BlazorPeliculasSa.Shared.Entidades.PeliculaActor", b =>
                {
                    b.Property<int>("PeliculaId")
                        .HasColumnType("int");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Personaje")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PeliculaId", "PersonaId");

                    b.HasIndex("PersonaId");

                    b.ToTable("PeliculasActores");
                });

            modelBuilder.Entity("BlazorPeliculasSa.Shared.Entidades.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Biografia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 100"
                        },
                        new
                        {
                            Id = 101,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 101"
                        },
                        new
                        {
                            Id = 102,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 102"
                        },
                        new
                        {
                            Id = 103,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 103"
                        },
                        new
                        {
                            Id = 104,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 104"
                        },
                        new
                        {
                            Id = 105,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 105"
                        },
                        new
                        {
                            Id = 106,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 106"
                        },
                        new
                        {
                            Id = 107,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 107"
                        },
                        new
                        {
                            Id = 108,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 108"
                        },
                        new
                        {
                            Id = 109,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 109"
                        },
                        new
                        {
                            Id = 110,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 110"
                        },
                        new
                        {
                            Id = 111,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 111"
                        },
                        new
                        {
                            Id = 112,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 112"
                        },
                        new
                        {
                            Id = 113,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 113"
                        },
                        new
                        {
                            Id = 114,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 114"
                        },
                        new
                        {
                            Id = 115,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 115"
                        },
                        new
                        {
                            Id = 116,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 116"
                        },
                        new
                        {
                            Id = 117,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 117"
                        },
                        new
                        {
                            Id = 118,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 118"
                        },
                        new
                        {
                            Id = 119,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 119"
                        },
                        new
                        {
                            Id = 120,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 120"
                        },
                        new
                        {
                            Id = 121,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 121"
                        },
                        new
                        {
                            Id = 122,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 122"
                        },
                        new
                        {
                            Id = 123,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 123"
                        },
                        new
                        {
                            Id = 124,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 124"
                        },
                        new
                        {
                            Id = 125,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 125"
                        },
                        new
                        {
                            Id = 126,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 126"
                        },
                        new
                        {
                            Id = 127,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 127"
                        },
                        new
                        {
                            Id = 128,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 128"
                        },
                        new
                        {
                            Id = 129,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 129"
                        },
                        new
                        {
                            Id = 130,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 130"
                        },
                        new
                        {
                            Id = 131,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 131"
                        },
                        new
                        {
                            Id = 132,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 132"
                        },
                        new
                        {
                            Id = 133,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 133"
                        },
                        new
                        {
                            Id = 134,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 134"
                        },
                        new
                        {
                            Id = 135,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 135"
                        },
                        new
                        {
                            Id = 136,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 136"
                        },
                        new
                        {
                            Id = 137,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 137"
                        },
                        new
                        {
                            Id = 138,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 138"
                        },
                        new
                        {
                            Id = 139,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 139"
                        },
                        new
                        {
                            Id = 140,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 140"
                        },
                        new
                        {
                            Id = 141,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 141"
                        },
                        new
                        {
                            Id = 142,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 142"
                        },
                        new
                        {
                            Id = 143,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 143"
                        },
                        new
                        {
                            Id = 144,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 144"
                        },
                        new
                        {
                            Id = 145,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 145"
                        },
                        new
                        {
                            Id = 146,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 146"
                        },
                        new
                        {
                            Id = 147,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 147"
                        },
                        new
                        {
                            Id = 148,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 148"
                        },
                        new
                        {
                            Id = 149,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 149"
                        },
                        new
                        {
                            Id = 150,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 150"
                        },
                        new
                        {
                            Id = 151,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 151"
                        },
                        new
                        {
                            Id = 152,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 152"
                        },
                        new
                        {
                            Id = 153,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 153"
                        },
                        new
                        {
                            Id = 154,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 154"
                        },
                        new
                        {
                            Id = 155,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 155"
                        },
                        new
                        {
                            Id = 156,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 156"
                        },
                        new
                        {
                            Id = 157,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 157"
                        },
                        new
                        {
                            Id = 158,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 158"
                        },
                        new
                        {
                            Id = 159,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 159"
                        },
                        new
                        {
                            Id = 160,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 160"
                        },
                        new
                        {
                            Id = 161,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 161"
                        },
                        new
                        {
                            Id = 162,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 162"
                        },
                        new
                        {
                            Id = 163,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 163"
                        },
                        new
                        {
                            Id = 164,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 164"
                        },
                        new
                        {
                            Id = 165,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 165"
                        },
                        new
                        {
                            Id = 166,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 166"
                        },
                        new
                        {
                            Id = 167,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 167"
                        },
                        new
                        {
                            Id = 168,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 168"
                        },
                        new
                        {
                            Id = 169,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 169"
                        },
                        new
                        {
                            Id = 170,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 170"
                        },
                        new
                        {
                            Id = 171,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 171"
                        },
                        new
                        {
                            Id = 172,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 172"
                        },
                        new
                        {
                            Id = 173,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 173"
                        },
                        new
                        {
                            Id = 174,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 174"
                        },
                        new
                        {
                            Id = 175,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 175"
                        },
                        new
                        {
                            Id = 176,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 176"
                        },
                        new
                        {
                            Id = 177,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 177"
                        },
                        new
                        {
                            Id = 178,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 178"
                        },
                        new
                        {
                            Id = 179,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 179"
                        },
                        new
                        {
                            Id = 180,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 180"
                        },
                        new
                        {
                            Id = 181,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 181"
                        },
                        new
                        {
                            Id = 182,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 182"
                        },
                        new
                        {
                            Id = 183,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 183"
                        },
                        new
                        {
                            Id = 184,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 184"
                        },
                        new
                        {
                            Id = 185,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 185"
                        },
                        new
                        {
                            Id = 186,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 186"
                        },
                        new
                        {
                            Id = 187,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 187"
                        },
                        new
                        {
                            Id = 188,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 188"
                        },
                        new
                        {
                            Id = 189,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 189"
                        },
                        new
                        {
                            Id = 190,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 190"
                        },
                        new
                        {
                            Id = 191,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 191"
                        },
                        new
                        {
                            Id = 192,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 192"
                        },
                        new
                        {
                            Id = 193,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 193"
                        },
                        new
                        {
                            Id = 194,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 194"
                        },
                        new
                        {
                            Id = 195,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 195"
                        },
                        new
                        {
                            Id = 196,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 196"
                        },
                        new
                        {
                            Id = 197,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 197"
                        },
                        new
                        {
                            Id = 198,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 198"
                        },
                        new
                        {
                            Id = 199,
                            FechaNacimiento = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Persona 199"
                        });
                });

            modelBuilder.Entity("BlazorPeliculasSa.Shared.Entidades.GeneroPelicula", b =>
                {
                    b.HasOne("BlazorPeliculasSa.Shared.Entidades.Genero", "Genero")
                        .WithMany("GeneroPeliculas")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorPeliculasSa.Shared.Entidades.Pelicula", "Pelicula")
                        .WithMany("GeneroPelicula")
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorPeliculasSa.Shared.Entidades.PeliculaActor", b =>
                {
                    b.HasOne("BlazorPeliculasSa.Shared.Entidades.Pelicula", "Pelicula")
                        .WithMany("PeliculaActor")
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorPeliculasSa.Shared.Entidades.Persona", "Persona")
                        .WithMany("PeliculaActor")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
